### ISSUE TITLE
It only says Hi to me

### ISSUE THREAD

**Issue by nickwanninger** [nickwanninger/gitpres#3]
The python program only says hello to me, I feel like it should say hi to anyone who runs it

PRs appreciated!

**Comment by apeckstl** [comment]
I think input() in python would work, but I don’t really have time to fix it

**Comment by apeckstl** [comment]
[Forking.Pull.Request.pdf](https://github.com/nickwanninger/gitpres/files/3798973/Forking.Pull.Request.pdf)

**Comment by nickwanninger** [comment]
thanks for the help everyone!
